### ISSUE TITLE
403 access denied when pulling a resource from https://get.pulumi.com

### ISSUE THREAD

**Issue by robertregnier** [pulumi/get.pulumi.com#142]
### What happened?

Diagnostics:
  pulumi:providers:fusionauth (fusion-auth):
    error: Could not automatically download and install resource plugin 'pulumi-resource-fusionauth' at version v2.0.0, install the plugin using `pulumi plugin install resource fusionauth v2.0.0`.
    Underlying error: error downloading plugin fusionauth to file: failed to download plugin: fusionauth-2.0.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-fusionauth-v2.0.0-windows-amd64.tar.gz

### Steps to reproduce

I created a very simply Pulumi script in dotnet. When I `pulumi up` the error occurs. Navigating to that url from my browser gives the same access denied error.

### Expected Behavior

I should be able to download the resource successfully.

### Actual Behavior

https://get.pulumi.com

### Output of `pulumi about`

c:\Projects\Scrum\fusion-auth>pulumi about
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  fusionauth-scrumorg -> c:\Projects\Scrum\fusion-auth\bin\Debug\net6.0\fusionauth-scrumorg.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.19

'dotnet build -nologo .' completed successfully
CLI
Version      3.52.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
dotnet      unknown
fusionauth  2.0.0

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='6.0.113'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/canrobbo
User           canrobbo
Organizations  canrobbo

Dependencies:
NAME                    VERSION
Pulumi                  3.52.1
theogravity.Fusionauth  2.0.0

Pulumi locates its logs in C:\Users\rober\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is a third-party provider (https://github.com/theogravity/pulumi-fusionauth) and so isn't published to get.pulumi.com.
This is probably the same issue as https://github.com/pulumi/pulumi/issues/10882.

For now you should be able to install with `pulumi plugin install resource fusionauth v2.0.1 --server github:
//api.github.com/theogravity`.
