### ISSUE TITLE
install.sh script does not add to ~/.bashrc or ~/.bash_profile in some cases

### ISSUE THREAD

**Issue by ellismg** [pulumi/get.pulumi.com#18]
The install script relies on `$SHELL` resolving to something so we can try to determine your shell and understand what `.profile` file to edit.

In the Azure Cloud Console, this wasn't working.  It turns out in that environment, `$SHELL` is not defined in your environment block.  However, `bash` is able to be able to give you back a path for `$SHELL` anyway.  But, since we tell folks to pipe through `sh`, which in the cloud shell is also a link to `dash` instead of `bash` (something Ubuntu does), we don't know what shell we are on and so we don't edit the right file.

I'm not 100% sure what we'll do here to address this.  Ideally we'll detect this case and edit the correct file (which I suspect is still `~/.bashrc`, but we'll have to read more about that).

https://wiki.ubuntu.com/DashAsBinSh is a good page on the differences and lets us know that we should not use bashisms in our install script if possible.

**Comment by joeduffy** [comment]
@ellismg I assume we're going to make a more aggressive move towards package managers during M19, and don't need to do this after all?

**Comment by ellismg** [comment]
Yeah, probably just better to close for now.
