### ISSUE TITLE
Symlink Pulumi binaries to `/usr/local/bin`

### ISSUE THREAD

**Issue by joeduffy** [pulumi/get.pulumi.com#30]
We've seen a number of issues with people manually symlinking Pulumi binaries to `/usr/local/bin`. We also go to great lengths to add various settings to your `.rc` files so that binaries end up on your path.

I think we should just perform this symlinking for folks. It's much easier than what we're doing now -- especially when it comes to versioning and upgrading -- and it just leads to less install friction overall.

**Comment by lukehoban** [comment]
We'll focus on moving to real package managers.
