### ISSUE TITLE
Move CLI distro to real package managers

### ISSUE THREAD

**Issue by joeduffy** [pulumi/get.pulumi.com#31]
We have been appropriately shamed: https://twitter.com/Nick_Craver/status/1049823523701776384.

Furthermore, we've already run into numerous deficiencies in our home-grown installer script:

* We implemented our own custom upgrade nagging
* Lack of symlinking, which users often resort to doing themselves (which sometimes fails) (https://github.com/pulumi/get.pulumi.com/issues/30)
* Inability to install a specific version on Windows (https://github.com/pulumi/get.pulumi.com/issues/27)

Although the simplicity of the `curl`able script is "nice" (albeit scary and insecure), we should move away from it as our primary installation mechanism, in favor of true package managers.

We already have a Brew package, but it's community maintained. We should take ownership of it.

We should also either release into the official `apt-get` repository, or create our own custom source.

Finally, on Windows, we should publish a Chocolatey package.

**Comment by ellismg** [comment]
Tracking the work with: https://github.com/pulumi/pulumi/issues/1536
