### ISSUE TITLE
Update post-install instructions

### ISSUE THREAD

**Issue by joeduffy** [pulumi/get.pulumi.com#38]
After installation, we don't make any mention about PATHs. (I thought we used to.) And the "Next Steps" bit is a little confusing, as it gives you three options. We should have one, single, and clear next step.

**Comment by joeduffy** [comment]
@justinvp I assume you're looking at this with your overhaul of the installation and getting started process, so assigning to you for triage.

**Comment by justinvp** [comment]
I actually wasn't already looking at this, but I definitely want to streamline things here. I won't be able to get to it today, so moving to M22.

**Comment by justinvp** [comment]
Fix available in #43 which can be merged when the merged site is live.

**Comment by justinvp** [comment]
The work for this is done in #43, it's just blocked on unrelated Travis issues in that repo.
