### ISSUE TITLE
PowerShell installer can silently fail

### ISSUE THREAD

**Issue by joeduffy** [pulumi/get.pulumi.com#52]
During a recent workshop, we had a case where the PowerShell install command seemed to run and complete just fine, but apparently had failed (`pulumi` was not on the `%PATH%` afterwards). Unfortunately, in the moment we didn't capture an `%ERRORLEVEL%` so we are just assuming it failed due to permissions issues; it's possible the binary got added to the wrong place. We did verify that it wasn't in the standard user directory location.

Manually downloading and unzipping worked around the problem.

**Comment by joeduffy** [comment]
@stack72 please add any more details if you have any -- I know you jotted down the problem, but I didn't see an issue filed, so I created one while it's fresh in my memory.

**Comment by justinvp** [comment]
Haven't heard any recent cases of this. I'm inclined to close as no repro until we get a user report with repro steps.
